language: java
cache:
  directories:
  - $HOME/.m2
sudo: required
jdk:
- oraclejdk8
services:
- docker
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push r0487637/docker-travis-ci:destination-api